name: Deploy Static Site

on:
  push:
    branches:
    - main
    - amazon-ads

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

    - name: Setup just
      uses: extractions/setup-just@v1

    - name: Setup SAM CLI
      uses: aws-actions/setup-sam@v2

    - run: just env=prod infra --no-confirm-changeset

    - run: just env=prod deploy